export const merch = [
  {
    id: 1,
    product: "AV White and Blue Hat",
    price: 10,
    desc: "AV Hat with a White and Blue design",
    category: "Decals",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/34D3s9m/item-2.jpg',
  },
  {
    id: 2,
    product: "AV Sweatshirt Round Back",
    price: 40,
    desc: "Sweatshirt with a round AVNW logo on the back",
    category: "Sweatshirts",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/6PHyrpp/item-3.jpg',
  },
  {
    id: 3,
    product: "AVNW Shirt Round Back",
    price: 60,
    desc: "Shirt with a round AVNW logo on the back",
    category: "Hats",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/DGVfDn4/item-4.jpg',
  },
  {
    id: 4,
    product: "Shirt Square Back Colored",
    price: 40,
    desc: "Shirt with a AVNW on the back",
    category: "asdf",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/6vw6MmB/item-5.jpg',
  },
  {
    id: 5,
    product: "Sweatshirt Square Back Black and White",
    price: 20,
    desc: "Sweatshirt with a AVNW logo on the back",
    category: "dfg",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/0K6DC2s/item-6.jpg',
  },
  {
    id: 6,
    product: " PX Sweatshirt Square Back Red and White",
    price: 20,
    desc: "Sweatshirt with a PX on the back",
    category: "dfg",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/CwX6jm3/item-7.jpg',
  },
  {
    id: 7,
    product: "PX Red and White Hat",
    price: 20,
    desc: "Sweatshirt with a AVNW on the back",
    category: "dfg",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/FJNVJ4g/item-8.jpg',
  },
  {
    id: 8,
    product: "PX shirt Red and White",
    price: 20,
    desc: "Shirt with a PX logo on the back",
    category: "dfg",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/vDgqdwH/item-9.jpg',
  },
  {
    id: 9,
    product: "AVNW shirt round back White and Blue",
    price: 20,
    desc: "Shirt with a AVNW logo on the back",
    category: "dfg",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/ZhCbxsL/item-10.jpg',
  },
  {
    id: 10,
    product: "Shirt Round Back Black and White",
    price: 20,
    desc: "Shirt with a round AVNW log on the back",
    category: "Photos",
    quantity: 1,
    type: 'merch',
    image: 'https://i.ibb.co/SVDdfh0/item-1.jpg',
  },
  
]

export const user = {
  id: 1,
  name: "Snow Theflake",
  phone: "5043333333",
  email: "email@gmail.com",
  address: "2139 SE Road St",
  unit: "",
  city: "Portland",
  state: "OR",
  zip: "97223",
}

export const photographers = [
  {
    id: 1,
    name: 'Casey',
    bio: `'Hello, my names Casey! I'm from Mcminnville, Oregon. I was born and raised here in the PNW, and have had plenty of time to explore the Northwest. Photography for me personally, is a way to express how I feel, to allow me to explore the west coast, and meet locals along the way.Photography is such a passion for me, and because of this, I decided to start a photography company. Not just any company, but one that strives to exceed every requirement you have, for whatever photoshoot idea you want."`,
    profile_image: 'https://i.ibb.co/yWh3TMg/profile-IMG.jpg',
    insta_username: `dempsey2.o`,
  },
  {
    id: 2,
    name: 'Bryan',
    bio: `My name is Bryan loop. I grew up in Portland Oregon. I started doing photography back in 2009 when I was in high school.From there I graduated in 2011 from Benson Polytechnic. I would describe my photography to be clean and creative. I am quick to adapt to lighting. With all that I have learned I will let my work say the rest! I look forward to getting to know you now!”`,
    profile_image: 'https://i.ibb.co/m8pnwk0/profile-IMG.jpg',
    insta_username: 'loopsphotographypdx',
  },
  {
    id: 3,
    name: 'Chris',
    bio: `Hey! My name is Chris. I grew up in sunny San Diego and moved up here to the PNW about 4 years ago. Car culture has always been a part of my life.So simply put, I’m a car enthusiast with a camera. Cars aside, photography has been a passion of mine since high school and shows no signs of stopping anytime soon.`,
    profile_image: 'https://i.ibb.co/MDKXbR6/profile-IMG.jpg',
    insta_username: 'chillaxinphoto',
  },
  {
    id: 4,
    name: 'Nicole',
    bio: `Hello! My name is Nicole Lenz. I am based out of Vancouver, Washington and I have been shooting since 2015. Photography to me is a lifestyle and not just a hobby.I absolutely love being able to capture who people are, and the beauty a single image can hold.`,
    profile_image: 'https://i.ibb.co/tB3SkW6/profile-IMG.jpg',
    insta_username: 'nlenzphotography',
  }
]

export const merch_categories = [
  {
    id: "1",
    category: "Hats",
  },
  {
    id: "2",
    category: "Sweatshirts",
  },
  {
    id: "3",
    category: "Decals",
  },
  {
    id: "4",
    category: "Photos",
  },
]

export const services = [
  {
    id: '1',
    product: 'Car Shoot',
    desc: 'Up to 10 photos. Must be on Sunday before, or during RDM',
    price: 40,
    type: 'service',
    quantity: 1,
  },
  {
    id: '2',
    product: 'Portrait Session',
    desc: 'Up to 11 photos. Must be on Sunday before, or during RDM',
    price: 40,
    type: 'service',
    quantity: 1,
  },
  {
    id: '3',
    product: 'Wedding or Engagement',
    desc: 'Up to 12 photos. Must be on Sunday before, or during RDM',
    price: 40,
    type: 'service',
    quantity: 1,
  },
  {
    id: '4',
    product: 'Rolling Shots',
    desc: 'Up to 13 photos. Must be on Sunday before, or during RDM',
    price: 40,
    type: 'service',
    quantity: 1,
  },
  {
    id: '5',
    product: 'Family Session',
    desc: 'Up to 14 photos. Must be on Sunday before, or during RDM',
    price: 40,
    type: 'service',
    quantity: 1,
  },
]