import React from 'react';

export default React.createContext({
  user: [],
  photographers: [],
  curPhotographer: null,
  curGallery: [],
  cart: [],
  shootLocation: [],
  shootLocationToggle: false,
  basicInfoToggle: false,
  shippingInfoToggle: false,
  merch: [],
  services: [],
  filterList: [],
  cartError: false,
  serviceError: false,
  token: '',
  route: '',
  accountType: '',
  menuToggle: false,
  photographerEdit: [],
  serviceEditing: [],
  productEditing: [],
  deletePhotographerConfirmation: false,
  deleteServiceConfirmation: false,
  deleteProductConfirmation: false,
  adminPhotographerInteraction: '',
  adminServiceInteraction: '',
  adminProductInteraction: '',
  setLoginToken: (token, user) => {},
  getLoginToken: _ => {},
  handleSignout: _ => {},
  handleCart : (prod) => {},
  handleShootLocation: (el) => {},
  changeItemQuantity: (q, el) => {},
  getMerch: _ => {},
  setCurPhotographer: (el) => {},
  setCurGallery: (el) => {},
  handleShootLocationToggle: _ => {},
  handleBasicInfoToggle: _ => {},
  handlShippingInfoToggle: _ => {},
  handleServiceError: _ => {},
  setPreviousRoute: route => {},
  handleMenuToggle: _ => {},
  handleNewPhotographerName: (e) => {},
  setPhotographers: (el) => {},
  setServices: (el) => {},
  setProducts: (el) => {},
  getPhotographers: _ => {},
  setEditPhotographer: _ => {},
  setEditService: _ => {},
  setEditProduct: _ => {},
  handleDeletePhotographerConfirmation: _ => {},
  handleDeleteServiceConfirmation: _ => {},
  handleDeleteProductConfirmation: _ => {},
  handleAdminPhotographerInteraction: _ => {},
  handleAdminServiceInteraction: _ => {},
  handleAdminProductInteraction: _ => {},
  photographerEditRESET: _ => {},
  serviceEditingRESET: _ => {},
});