import React from 'react';

export default React.createContext({
  user: [],
  photographers: [],
  curPhotographer: null,
  curGallery: [],
  cart: [],
  shootLocation: [],
  shootLocationToggle: false,
  basicInfoToggle: false,
  shippingInfoToggle: false,
  merch: [],
  services: [],
  filterList: [],
  isUserAuthenticated: false,
  cartError: false,
  serviceError: false,
  token: '',
  route: '',
  setLoginToken: (token, user) => {},
  getLoginToken: _ => {},
  handleSignout: _ => {},
  // setLoginUser: user => {},
  handleCart : (prod) => {},
  handleShootLocation: (el) => {},
  changeItemQuantity: (q, el) => {},
  handleFilterList: (id) => {},
  getMerch: _ => {},
  setCurPhotographer: (el) => {},
  setCurGallery: (el) => {},
  handleShootLocationToggle: _ => {},
  handleBasicInfoToggle: _ => {},
  handlShippingInfoToggle: _ => {},
  handleServiceError: _ => {},
  setPreviousRoute: route => {}
});